# GitLab CI configuration for Rust project
image: rust:latest

# Cache cargo dependencies
variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cargo/
    - target/

# Define stages
stages:
  - format
  - check
  - lint
  - doc
  - test
  - build

# Before script to install necessary components
before_script:
  - rustc --version && cargo --version
  - rustup component add rustfmt clippy

# Format check
format:
  stage: format
  script:
    - cargo fmt --all -- --check
  allow_failure: false

# Cargo check
check:
  stage: check
  script:
    - cargo check --all-targets --all-features
  allow_failure: false

# Clippy linting
clippy:
  stage: lint
  script:
    - cargo clippy --all-targets --all-features -- -D warnings
  allow_failure: false

# Documentation check
doc:
  stage: doc
  script:
    - cargo doc --all --no-deps --document-private-items
  allow_failure: false

# Run tests
test:
  stage: test
  script:
    - cargo test --all-features --verbose
  coverage: '/^\d+\.\d+% coverage/'
  artifacts:
    reports:
      junit: test-results.xml
    expire_in: 1 week
  allow_failure: false

.build-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build-fuiz-server:
  extends: .build-image
  script:
    - docker build --pull --target fuiz-server -t $CI_REGISTRY_IMAGE/fuiz-server:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/fuiz-server:latest .
    - docker push $CI_REGISTRY_IMAGE/fuiz-server:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/fuiz-server:latest

build-corkboard-server:
  extends: .build-image
  script:
    - docker build --pull --target corkboard-server -t $CI_REGISTRY_IMAGE/corkboard-server:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/corkboard-server:latest .
    - docker push $CI_REGISTRY_IMAGE/corkboard-server:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/corkboard-server:latest
