"$schema" = "./node_modules/wrangler/config-schema.json"
name = "fuiz-cloudflare"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-17"

services = [{ binding = "COUNTER", service = "counter" }]

[build]
command = "cargo install -q worker-build && worker-build --release"

[durable_objects]
bindings = [
    { name = "GAME", class_name = "Game" },
    { name = "GAME_MANAGER", class_name = "GameManager" },
]


[[migrations]]
tag = "v1"
new_classes = ["Game"]


[[migrations]]
tag = "v2"
transferred_classes = [
    { from = "GameManager", to = "GameManager", from_script = "game_manager" },
]
